/** Differential test on hand-made Unicode / whitespace edge strings (fixture generated by the Python reference). */
import { describe, expect, it } from "vitest";
import golden from "../golden/edge_cases.json";
import { classify } from "../classify";
import { assignTier } from "../decide";
import { extract } from "../extract";
import { applyPass2, normalizeRecord } from "../normalize";
import { evaluatePair } from "../pair";
import { assets, diffs, mk } from "./helpers";

describe("unicode edge cases match Python", () => {
  it("records", () => {
    const cfg = assets.config;
    const failures: string[] = [];
    for (const g of golden.records as any[]) {
      const raw = mk(g.input);
      let norm = normalizeRecord(raw, cfg);
      const cls = classify(norm.norm_text, cfg);
      norm = applyPass2(norm, cls.class_code, cfg);
      const rec = assignTier(extract(raw, norm, cls, cfg), cfg);
      const actual = {
        normalized: norm.norm_text, uom: norm.uom_norm, transforms: norm.transforms, class_code: rec.class_code,
        class_confidence: rec.class_confidence, abstained: rec.abstained, tier: rec.tier, tier_reasons: rec.tier_reasons,
        attributes: rec.attributes, residuals: rec.residuals, sanity_flags: rec.sanity_flags, mfr_norm: rec.mfr_norm, mpn_norm: rec.mpn_norm,
      };
      const d = diffs(actual, g.expected);
      if (d.length) failures.push(`${JSON.stringify(g.input.maktx)}: ${d.slice(0, 3).join("; ")}`);
    }
    expect(failures).toEqual([]);
  });

  it("pairs", () => {
    const failures: string[] = [];
    for (const g of golden.pairs as any[]) {
      const p = evaluatePair(mk(g.left), mk(g.right), assets);
      const actual = {
        class_code: p.class_code, tier: p.tier, comparison: p.comparison, residual_diff: p.residual_diff, rules: p.rules, features: p.features,
        gate_score: p.gate_score, baseline_score: p.baseline_score, zone: p.zone, zone_step: p.zone_step, reason: p.zone_reason,
      };
      const d = diffs(actual, g.expected, 1e-9);
      if (d.length) failures.push(`${g.left.maktx} | ${g.right.maktx}: ${d.slice(0, 3).join("; ")}`);
    }
    expect(failures).toEqual([]);
  });
});
